### TEST SERVER
GET http://127.0.0.1:3333/
Content-Type: application/json

### REGISTER USER
POST http://127.0.0.1:3333/register
Content-Type: application/json

{
    "username": "thalia",
    "email": "thalialeticia1107@gmail.com",
    "password": "thalia"
}

### LOGIN USER
POST http://127.0.0.1:3333/login
Content-Type: application/json

{
    "email": "thalialeticia1107@gmail.com",
    "password": "thalia"
}

### LOGOUT USER
PATCH http://127.0.0.1:3333/logout
Content-Type: application/json
Authorization: Bearer Y2wxM2M5dTBkMDAwMG8zeG9idzZlOWZmbA.HAtD6T77cBRRemYkrf9DKzpiUOcMmSjUyz-YoWC1ZSC0r28abx8yD9LMqUFn

### CREATE FASKES
POST http://127.0.0.1:3333/faskes/
Content-Type: application/json
Authorization: Bearer Y2wxM2M5dTBkMDAwMG8zeG9idzZlOWZmbA.HAtD6T77cBRRemYkrf9DKzpiUOcMmSjUyz-YoWC1ZSC0r28abx8yD9LMqUFn

{
    "name": "Awal Bros",
    "faskes_type": "Puskesmas",
    "total_nakes": 5
}

### READ FASKES
GET http://127.0.0.1:3333/faskes
Content-Type: application/json
Authorization: Bearer Y2wxM2M5dTBkMDAwMG8zeG9idzZlOWZmbA.HAtD6T77cBRRemYkrf9DKzpiUOcMmSjUyz-YoWC1ZSC0r28abx8yD9LMqUFn